# Generated by Django 5.0 on 2024-01-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='trips',
            field=models.ManyToManyField(blank=True, to='tripbooking.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(blank=True, to='tripbooking.person'),
        ),
    ]
